### ISSUE TITLE
Fresh install throws vite:dep-scan error

### ISSUE THREAD

**Issue by Stolson** [umaranis/svelte-lexical#88]
I can reproduce this with:

> git clone git@github.com:umaranis/svelte-lexical.git
> cd svelte-lexical
> pnpm install 
> pnpm dev

Here's the error I get:

`Error:   Failed to scan for dependencies from entries:
  /Users/steveo/code/svelte-lexical/demos/playground/index.html
/Users/steveo/code/svelte-lexical/demos/playground/split/index.html

  ✘ [ERROR] Failed to resolve entry for package "svelte-lexical". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../../node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48264:17)
    at resolvePackageEntry (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48261:5)
    at tryNodeResolve (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
    at Context.resolveId (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47781:28)
    at Object.resolveId (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51063:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51388:26)
    at async file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51571:34
    at async requestCallbacks.on-resolve (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:22)
    at async handleRequest (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:732:11)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51561:19)
    at handlePlugins (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1293:21)
    at buildOrContextImpl (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:979:5)
    at Object.buildOrContext (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:788:5)
    at /Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:2224:68
    at new Promise (<anonymous>)
    at Object.context (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:2224:27)
    at Object.context (/Users/steveo/code/svelte-lexical/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:2048:58)
    at prepareEsbuildScanner (file:///Users/steveo/code/svelte-lexical/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51335:26)

  The plugin "vite:dep-scan" was triggered by this import

    script:/Users/steveo/code/svelte-lexical/demos/playground/src/RichTextComposer.svelte?id=0:43:9:
      43 │   } from 'svelte-lexical';
         ╵          ~~~~~~~~~~~~~~~~

`

**Comment by Stolson** [comment]
Apologies, fixed with the following:

> cd packages/svelte-lexical
> pnpm build
